//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiende_De_Video_Juegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public long IdPrestamo { get; set; }
        public string UsuarioCedula { get; set; }
        public long VideoJuegoCodigo { get; set; }
        public long VideoJuegoCodigoEjemplar { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual videoJuego videoJuego { get; set; }
    }
}
